version: '3'
services:
  db:
    image: habitat/postgresql
  miniflux:
    image: cnunciato/miniflux
    ports:
      - "80:8080"
    links:
      - db
    command: --peer db --bind db:postgresql.default
